enum CitiesTypeKeys {
    GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS",
    GET_CITIES_FAIL = "GET_CITIES_FAIL",   
    GET_CURRENT_CITIES_SUCCESS = "GET_CURRENT_CITIES_SUCCESS",
    GET_CURRENT_CITIES_FAIL = "GET_CURRENT_CITIES_FAIL", 
  }
  
export default CitiesTypeKeys;